//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public int id { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public System.DateTime fecha_bd { get; set; }
        public string tipo_sangre { get; set; }
        public string seguro { get; set; }
        public string tipo_consulta { get; set; }
        public string doctor { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public int precio { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual consulta consulta { get; set; }
    }
}
