//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class basedatoFinal3Entities : DbContext
    {
        public basedatoFinal3Entities()
            : base("name=basedatoFinal3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asistente> asistente { get; set; }
        public virtual DbSet<cita> cita { get; set; }
        public virtual DbSet<consulta> consulta { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<receta> receta { get; set; }
        public virtual DbSet<visita> visita { get; set; }
        public virtual DbSet<recaudado> recaudado { get; set; }
    }
}
